version: '3.8'

services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
        - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
        - VITE_NYT_API_KEY=${VITE_NYT_API_KEY}
    ports:
      - "8080:3000"
    restart: unless-stopped
    container_name: news-aggregator
    environment:
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
      - VITE_NYT_API_KEY=${VITE_NYT_API_KEY}